version: '3.8'

services:
  nbiot_api_service:
    image: minhtuan172/nbiot-detector-app 
    container_name: nbiot_api_container 
    ports:
      - "8000:8000"
    restart: unless-stopped 

networks:
  default:
    driver: bridge