version: '3.8'

services:
  nbiot_api_service_local:
    build:
      context: .
      dockerfile: Dockerfile
    image: nbiot-detector-api-slim:latest
    container_name: nbiot_api_container
    ports:
      - "8000:8000" 
    restart: unless-stopped

networks:
  default:
    driver: bridge